"""create refresh token in DB

Revision ID: 0157aa016058
Revises: 9b2a98329b9a
Create Date: 2025-10-22 11:26:28.756117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0157aa016058'
down_revision: Union[str, Sequence[str], None] = '9b2a98329b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expired_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_refreshtokens_user_id'), 'refreshtokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_user_id'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    # ### end Alembic commands ###
